language: go
go:
    - 1.7
    - tip
env:
    global:
        - GOARCH=amd64
install:
    - go get -v github.com/Masterminds/glide
    - cd $GOAPTH/github.com/Masterminds/glide && git checkout v0.12.3
    - glide install
script:
    - go test -v ./bolt
notifications:
    email: false
matrix:
    allow_failures:
        - go: tip

