language: go
go:
    - 1.7.x
    - 1.8.x
    - tip
env:
    global:
        - GOARCH=amd64
install:
    - mkdir $GOPATH/bin
    - glide --version || go get -u -f github.com/Masterminds/glide
    - glide install
    - go generate ./cmd/drawrserver
script:
    - go test -v ./pkg/...
notifications:
    email: false
matrix:
    allow_failures:
        - go: tip

