language: go
go:
    - 1.7
    - tip
env:
    global:
        - GOARCH=amd64
install:
    - mkdir $GOPATH/bin
    - curl https://glide.sh/get | sh
    - glide install
    - go generate ./cmd/drawrserver
script:
    - go test -v ./bolt
notifications:
    email: false
matrix:
    allow_failures:
        - go: tip

