#!/bin/bash

VERSION=$(git describe --tags)
TIME=$(date)
REPO="github.com/drawr-team/core-server"
FILE="version.go"

vString="drawrserver ${VERSION}\nfrom ${REPO}\ncompiled at <${TIME}>\n"

cat << EOF > ${FILE}
// THIS FILE IS AUTOGENERATED BY go:generate
// DO NOT EDIT!
package main

//go:generate bash ./version.sh
const version = "${vString}"
EOF
