// THIS FILE IS AUTOGENERATED BY go:generate
// DO NOT EDIT!
package main

//go:generate bash ./version.sh
const version = "drawrserver v0.2.3\nfrom github.com/drawr-team/core-server\ncompiled at <Sun Jan 22 20:57:15 CET 2017>\n"
