// THIS FILE IS AUTOGENERATED BY go:generate
// DO NOT EDIT!
package main

//go:generate bash ./version.sh
const version = "drawrserver v0.2.4\nfrom github.com/drawr-team/core-server\ncompiled at <Wed Feb 22 15:54:30 CET 2017>\n"
